language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create user testdbuser with password \'password\''
  - psql -U testdbuser -a -f sql/install.sql
after_script:
  - psql -U testdbuser -a -f sql/uninstall.sql
