language: node_js
matrix:
  include:
  - node_js: "9"
  - node_js: "8"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -U testdbuser -a -f sql/install.sql
after_script:
  - psql -U testdbuser -a -f sql/uninstall.sql
