language: node_js
node_js:
  - node
env:
  - NODE_ENV=test
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE ROLE testdbuser PASSWORD 'password' CREATEDB LOGIN"
  - psql -c 'CREATE DATABASE testdbuser OWNER testdbuser'
  - yarn install:database
after_script:
  - yarn uninstall:database
