language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "create user testdbuser with password 'password'"
  - psql -c "create database testdbuser owner testdbuser"
  - yarn install:database -U testdbuser
after_script:
  - yarn uninstall:database -U testdbuser
