language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE ROLE testdbuser PASSWORD 'password' CREATEDB"
  - psql -c 'CREATE DATABASE testdbuser OWNER testdbuser'
  - yarn install:database
after_script:
  - yarn uninstall:database
