language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - mkdir ./config
  - cp ./database.yml.travis ./config/database.yml
  - psql -U testdbuser -a -f sql/install.sql
after_script:
  - psql -U testdbuser -a -f sql/uninstall.sql
